name: muslim
description: "Quran Reader & Player"
publish_to: "none"
version: 0.2.1+4

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  just_audio: ^0.10.5
  intl: ^0.20.2
  http: ^1.6.0
  shared_preferences: ^2.5.4
  google_fonts: ^8.0.1
  awesome_notifications: ^0.10.1
  just_audio_background: ^0.0.1-beta.17
  audio_service: ^0.18.18
  permission_handler: ^12.0.1
  flutter_qiblah: ^3.2.0
  flutter_bloc: ^9.1.1
  geolocator: ^14.0.2
  adhan: ^2.0.0+1
  hijri: ^3.0.0
  geocoding: ^4.0.0
  disable_battery_optimization: ^1.1.2
  share_plus: ^12.0.1
  skeletonizer: ^2.1.2
  latlong2: ^0.9.1
  workmanager: ^0.9.0+3
  syncfusion_flutter_sliders: ^32.2.4
  url_launcher: ^6.3.2
  in_app_update: ^4.2.5
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  in_app_review: ^2.0.11
  scrollable_positioned_list: ^0.3.8
  internet_state_manager: ^1.10.1+3
  flutter_screenutil: ^5.9.3
  get_it: ^9.2.0
  equatable: ^2.0.8
  quran: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/kaaba.png
    - assets/images/muslim_logo.png
    - assets/json/azkar.json
    - assets/json/zekr.json
    - assets/json/azkar_en.json
    - assets/json/names_of_allah.json
    - assets/home/
    - assets/quran/
    - assets/hadith/
    - assets/qiblah/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/muslim_logo.png"
  min_sdk_android: 21
